server:
  port: 8090
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lris?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  memcache:
    # memcached服务器节点
    servers: 192.168.108.57:11211
    # nio连接池的数量
    poolSize: 10
    # 设置默认操作超时
    opTimeout: 3000
    # 是否启用url encode机制
    sanitizeKeys: false
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
  thymeleaf:
    # 默认路径
    prefix: classpath:/templates/
    # 后缀
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
      cache: false
  data:                        #芒果db配置
      mongodb:
        host: 192.168.108.57
        port: 30000
        database: collection_2019
        username: manager
        password: 20180101
        authentication-database: admin

#rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
